### ISSUE TITLE
Suppress diagnostics

### ISSUE THREAD

**Issue by grylem** [slewsys/ed#1]
Hi
echo a >file
printf ',s/a/b/g\nw\nq' | ed -s file
?
why the ed will show a question mark?
Regards.

**Comment by slewsys** [comment]
First of all, ed  prints diagnostics given option **-v**.  In the case of your script:

```shell
printf ',s/a/b/g\nw\nq' | ed -v file
```
I get:

> 2
> 2
> ?
> End-of-file unexpected

So if I were editing interactively, it's as though I hit **^D** (i.e., EOF) after typing **q**.  Ed is expecting an EOL, not an EOF.  Arguably, it could be smarter about handling this particular case.  In the mean time, you could either append a newline after **q** or even just omit it altogether.  Since the file was successfully written, ed won't complain about an EOF on a line by itself.

Hope that helps.  Thank you for the report!

**Comment by grylem** [comment]
Thanks for clarifying.
Why i asked about it - macOS and OpenBSD version of ed show nothing in this case.
So for this version is it correct?
printf ',s/a/b/g\nw\nq\n' | .ed -s file
or is it better to use like this?
printf '%s\n' ',s/a/b/g' w q | ed -s file
Many thanks.
P.S.
can you have a similar version of ex?

**Comment by slewsys** [comment]
The macOS and OpenBSD versions of ed, which are essentially the same, explicitly discard (command) lines that do not end with a newline.  They set an error message, but don't report it.  One consequence of this is that while your example appears to work, substituting in your script **wq**  in place of **w\nq** does not, i.e., 

```bash
printf`` ',s/a/b/g\nwq' | ed  file
```

fails.  This may be one reason that the current implementation was changed.  Nonetheless, it seems reasonable to me to expect that the last line of a script is executed, even if not newline-delimited.  So it's something that I'll explore.

**Comment by slewsys** [comment]
> can you have a similar version of ex?

This version ed has a number of  (mostly undocumented) extensions available as configure options, e.g., file globbing (if configured with **--enable-file-glob**) and external filters (if configured with **--enable-external-filter**).  But no, I never considered writing another ex.  In addition to vim, there is nvi, written for *BSD which is much closer to Bill Joy's version.

**Comment by grylem** [comment]
a couple more questions:
why does it work in this version of the ed without any args?
echo -e 'a\nb\nc' >file
`printf '%s\n' ',s/\(a\|b\)/e/g' ,p q | ed -s file`
e
e
c
The classic version of ed use BRE where not alternation "|" etc.
Do you have any plans to add argument -S like in NetBSD version? Where -S is "Disables using of the ! command"?
Regards.

**Comment by slewsys** [comment]
There are run-time options (**-r** and **-E**) to enable extended regular expressions, but they shouldn't be enabled by default.  I'm curious, on what system do you see this?  Maybe ed got linked against an unusual regex library?

> Do you have any plans to add argument -S like in NetBSD version?

I have to take a look at NetBSD.  If `red` is symlinked against ed, I'm guessing  that `red` (= restricted ed) is the same as NetBSD's `ed -S`?  Changing the behavior of a program based on the name is considered bad practice, which may be why NetBSD introduced **-S**?

**Comment by grylem** [comment]
Sorry brought an invalid example
`printf '%s\n' ',s/\(a\|b\)/e/g' ,p q | ed -s file`
But in anyway it should not be so it seems to me.

> I'm curious, on what system do you see this?

macOS.
Now in my case:
./configure --disable-nls --enable-all-extensions
Several warnings like
exec.c:556:44: warning: format string is empty [-Wformat-zero-length]
        printf (ed->exec->opt & SCRIPTED ? "" : "%s\n", ed->file->name);
and some others.

Option '-s' does not suppress message completely.
The ed uses ERE(and other) instead BRE. 

>I have to take a look at NetBSD. If red is symlinked against ed, I'm guessing that red (= restricted ed) is the same as NetBSD's ed -S?

Yes. Maybe you can do the same?

**Comment by slewsys** [comment]
I've verified that on macOS 10.13.6, configuring with  **--enable-all-extensions**  is not adequate.  Many of the tests fail (you can try running `make check` from the top-level source directory to see what I mean).  However, adding the configure option **--with-included-regex** allows all of the tests to complete successfully.

**Comment by slewsys** [comment]
> printf '%s\n' ',s/(a|b)/e/g' ,p q | ed -s file
> But in anyway it should not be so it seems to me.

Linking against GNU regex as indicated in the previous comment seems to resolve this issue too.  Apple may have updated their regular expression library, because it worked at one time.  I'll take a look as time permits.  Thank you for bringing this to my attention!

**Comment by grylem** [comment]
Thanks

**Comment by slewsys** [comment]
> Do you have any plans to add argument -S like in NetBSD version? Where -S is "Disables using of the ! command"?

Looking at NetBSD's implementation of **-S**,  I see it disables external commands but does not restrict access to the filesystem as red does.  If you are letting an untrusted program execute ed scripts, wouldn't restricting filesystem access be desirable too?
